version: "3"

services:
  dns:
    build:
      context: .
      dockerfile: dns.Dockerfile
    networks:
      - dnsnet
    tty: true
    stdin_open: true
    
  manager:
    build:
      context: .
      dockerfile: manager.Dockerfile
    depends_on:
      - dns
    networks:
      - dnsnet
    tty: true
    stdin_open: true

networks:
  dnsnet: